### ISSUE TITLE
What's the point of setup.py?

### ISSUE THREAD

**Issue by ngbusca** [igmhub/pyLyA#136]
@slosar You recently introduced the python setup.py install scheme which seems to me a just fancy way of editing appropriately PATH and PYTHONPATH, only that:

* it doesn't do that but rather creates a bunch of files un difficult to track locations, which
* makes it hard to uninstall (there is no python setup.py uninstall!!), and
* you have to remember to do python setup.py install again every time you make a change in the code
* in some machines it also creates build, dist, py/pyLyA.egg_info (??) directories that are untracked by git (should we track them or add them to .gitignore?)

Is there any advantage to this?

**Comment by slosar** [comment]
True, there is no uninstall and I also hate that (but there are plenty of recipes on the internet). However:

 * Eventually, you hope you will get sufficient users that will use pylya as stable module, like numpy
 * Once you have setup script, it is easy to get into pip, etc, so that people can just do `pip install pylya`
 * You don't actually need that and can continue using `PYTHONPATH` if you wish so, for e.g. development.
 * There is this social element where my code was often looked down upon because I didn't have the `setup.py`. People just think it is a basic software engineering practice.

**Comment by ngbusca** [comment]
Ok, that makes sense...
